language: node_js
node_js:
- '5.2.0'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_97eee709fa5f_key -iv $encrypted_97eee709fa5f_iv
  -in travis.enc -out ~/.ssh/travis -d
- chmod 600 ~/.ssh/travis
- eval $(ssh-agent)
- ssh-add ~/.ssh/travis
- cp ssh_config ~/.ssh/config
- git config --global user.name "asjmtz"
- git config --global user.email asjmtz@163.com
install:
- npm install hexo-cli -g
- npm install
- npm install hexo-generator-feed --save
- npm install hexo-deployer-git --save
- npm install hexo-generator-sitemap --save
script:
- hexo clean
- hexo generate
- hexo deploy